#!/usr/bin/expect -f

set HOST "47.244.152.59"
set PORT "22"
set USER "wp_sftp_user"
set PASS "WPsftp@0420"
set LOCALDIR "/Users/nelson/corp-site/build"
set DESTDIR "/data/www/test.ahimhk.com/wordpress"

set timeout 300

# Use tar through sshpass
spawn bash -c "sshpass -p $PASS tar cf - -C $LOCALDIR . | sftp -P $PORT -p $USER@$HOST:$DESTDIR"
expect {
    "password:" {
        send "$PASS\r"
    }
    eof {
        puts "Done"
    }
}
expect eof
